version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - jenkins-home:/var/jenkins_home
    ports:
        - 8080:8080
        - 50000:50000

volumes:
  jenkins-home: