version: '3.7'

services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: dsandoval571/generator:multi
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"